app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

blast_core:
    resource: "@BlastCoreBundle/Resources/config/routing.yml" 
    prefix:   /admin
    
librinfo_media:
    resource: "@LibrinfoMediaBundle/Resources/config/routing.yml"
