# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    sylius.canonicalizer:
        class: Sylius\Component\User\Canonicalizer\Canonicalizer