<?php

namespace Librinfo\VarietiesBundle\DependencyInjection\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 14:45:10.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\DependencyInjection\LibrinfoVarietiesExtension;
use Matthias\SymfonyDependencyInjectionTest\PhpUnit\AbstractExtensionTestCase;

class LibrinfoVarietiesExtensionTest extends AbstractExtensionTestCase
{
    /**
     * @var LibrinfoVarietiesExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    $this->object = new LibrinfoVarietiesExtension;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\DependencyInjection\LibrinfoVarietiesExtension::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {// Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
//        $this->container->setParameter('kernel.bundles', array('librinfo_varieties.code_generator.species' => 'whatever'));
//        $this->object->load();


    }
        protected function getContainerExtensions()
    {
        return array(
            new LibrinfoVarietiesExtension()
        );
    }
}
